# Generated by Django 5.1.1 on 2024-10-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='commenrs',
            new_name='comments',
        ),
    ]
